version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000 & python -m daphne -b 0.0.0.0 -p 8001 fanshub.asgi_dev:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=fanshub.settings
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - WEBSOCKET_URL=ws://localhost:8001
    restart: always

volumes:
  redis_data: 