# Generated by Django 5.1.7 on 2025-03-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_savedpaymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='stripe_payment_method_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
