# Generated by Django 5.1.7 on 2025-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_media_thumbnail_post_title_alter_media_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('subscribers', 'Subscribers Only - Visible to subscribers'), ('premium', 'Premium - Requires additional payment')], default='public', help_text='Choose who can see this post', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for premium content (only if visibility is set to Premium)', max_digits=10, null=True),
        ),
    ]
